"""Structured, machine-readable data-shape profile per object (ROADMAP #83).

`describe()` tells you an object's *structure* (fields, types, relationships,
required flags). It can't tell you its *behavior* -- what the platform
auto-creates, what's really populated, what automation fires. This module
aggregates the behavioral signals the framework already produces into one
per-object JSON profile a tool can reason over:

- **structure** -- from live `describe()` (key/required fields, parent lookups).
- **automation** -- from `analyze-org-risk`'s `ObjectAutomationRisk` (active
  validation rules / triggers / flows / workflow rules / approval processes).
- **auto_generated_children** -- from `child_record_risk.py`'s empirical
  detection (rows in `ObjectAutomationRisk` with `CheckType =
  AutoGeneratedChildRecord`) -- the Tooling-API-invisible platform automation
  that a plain metadata read misses entirely.
- **field_population** -- from `profile-salesforce`'s `FieldProfile` (real
  populated %, distinct counts) -- how the data actually lives, not just what
  the schema allows.

Read-only. `build_profile()` returns a dict; the CLI writes it to JSON and
prints a summary. Missing upstream signals are reported as `scanned: false` /
`profiled: false`, never as a silently-clean zero -- a not-yet-run
`analyze-org-risk` is different from "no automation".
"""
import datetime
import json
import os

from sqlalchemy import text

import sql_dialect


def _describe_structure(sf, object_name):
    d = getattr(sf, object_name).describe()
    key_fields = []
    parent_lookups = []
    for f in d["fields"]:
        if f.get("type") == "reference" and f.get("referenceTo") and f.get("createable"):
            parent_lookups.append({
                "field": f["name"],
                "references": list(f["referenceTo"]),
                "relationshipName": f.get("relationshipName"),
            })
        # "required in practice" = not nillable AND not platform-defaulted
        required = (not f.get("nillable", True)) and (not f.get("defaultedOnCreate", False))
        if required or f.get("externalId") or f["name"] == "Name":
            key_fields.append({
                "name": f["name"],
                "type": f.get("type"),
                "required": bool(required),
                "createable": bool(f.get("createable")),
                "updateable": bool(f.get("updateable")),
                "defaultedOnCreate": bool(f.get("defaultedOnCreate")),
                "externalId": bool(f.get("externalId")),
            })
    # Surface same-object start/end date pairs (ROADMAP #88) so the ordering
    # risk is visible per object -- reuses snowfakery_data's own heuristic so
    # the profile and the mock generator agree on what a "date range" is.
    # Lazy import: keep this module light unless a profile is actually built.
    import snowfakery_data as _sfd
    date_names = [f["name"] for f in d["fields"]
                  if f.get("type") in ("date", "datetime")]
    date_range_pairs = [{"start": s, "end": e}
                        for s, e in _sfd.date_range_pairs(date_names)]

    return {
        "custom": bool(d.get("custom")),
        "key_fields": key_fields,
        "parent_lookups": parent_lookups,
        "date_range_pairs": date_range_pairs,
    }


def _automation_and_children(engine, object_name, schema):
    """Returns (automation_dict, auto_generated_children_list) from
    ObjectAutomationRisk. automation['scanned'] is False (not an empty
    count) when analyze-org-risk hasn't populated the table for this org."""
    d = sql_dialect.for_engine(engine)
    if not d.table_exists(engine, schema, "ObjectAutomationRisk"):
        return {"scanned": False}, []
    with engine.begin() as cx:
        rows = cx.execute(
            text(
                f"SELECT CheckType, ItemName, IsActive, DirectHit, Detail "
                f"FROM {d.qualify(schema, 'ObjectAutomationRisk')} "
                f"WHERE ObjectName = :obj"
            ),
            {"obj": object_name},
        ).mappings().all()
    rows = [sql_dialect.lower_keys(r) for r in rows]
    if not rows:
        # table exists but this object was never scanned
        return {"scanned": False}, []
    active_counts = {}
    auto_children = []
    for r in rows:
        ct = r.get("checktype")
        if ct == "AutoGeneratedChildRecord":
            auto_children.append({"child": r.get("itemname"), "detail": r.get("detail")})
        elif r.get("isactive"):
            active_counts[ct] = active_counts.get(ct, 0) + 1
    return {"scanned": True, "active_counts": active_counts}, auto_children


def _field_population(engine, object_name, schema):
    d = sql_dialect.for_engine(engine)
    if not d.table_exists(engine, schema, "FieldProfile"):
        return {"profiled": False}
    with engine.begin() as cx:
        rows = cx.execute(
            text(
                f"SELECT FieldName, PopulatedPct, DistinctCount, TotalRows "
                f"FROM {d.qualify(schema, 'FieldProfile')} "
                f"WHERE ObjectOrTable = :obj"
            ),
            {"obj": object_name},
        ).mappings().all()
    rows = [sql_dialect.lower_keys(r) for r in rows]
    if not rows:
        return {"profiled": False}
    fields = [{
        "name": r.get("fieldname"),
        "populated_pct": r.get("populatedpct"),
        "distinct": r.get("distinctcount"),
    } for r in rows]
    return {"profiled": True, "total_rows": rows[0].get("totalrows"), "fields": fields}


def build_profile(sf, engine, object_name, schema="dbo", org_alias=None):
    """Assemble the full data-shape profile dict for one object."""
    automation, auto_children = _automation_and_children(engine, object_name, schema)
    return {
        "object": object_name,
        "org_alias": org_alias,
        "generated": datetime.date.today().isoformat(),
        "structure": _describe_structure(sf, object_name),
        "automation": automation,
        "auto_generated_children": auto_children,
        "field_population": _field_population(engine, object_name, schema),
    }


def profile_path(object_name, output_dir="data_shapes"):
    return os.path.join(output_dir, f"{object_name}.json")


def write_profile(profile, output_dir="data_shapes"):
    os.makedirs(output_dir, exist_ok=True)
    path = profile_path(profile["object"], output_dir)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(profile, fh, indent=2)
    return path


def load_profile(object_name, output_dir="data_shapes"):
    """Read a previously-built profile, or None if it doesn't exist -- the
    read-only surfacing side (show-data-shape), analogous to okf_lookup."""
    path = profile_path(object_name, output_dir)
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def summary_lines(profile):
    """Compact, human-readable lines describing a profile -- shared by the
    build and show CLI commands."""
    st = profile["structure"]
    au = profile["automation"]
    ac = profile["auto_generated_children"]
    fp = profile["field_population"]
    lines = [
        f"structure: {len(st['key_fields'])} key/required field(s), "
        f"{len(st['parent_lookups'])} parent lookup(s), custom={st['custom']}",
    ]
    drp = st.get("date_range_pairs") or []
    if drp:
        lines.append("date-range pairs (end must be >= start): "
                     + ", ".join(f"{p['start']}->{p['end']}" for p in drp))
    if au.get("scanned"):
        counts = au.get("active_counts") or {}
        lines.append("automation: " + (
            ", ".join(f"{k}={v}" for k, v in sorted(counts.items())) if counts
            else "no active automation found"))
    else:
        lines.append("automation: NOT scanned -- run analyze-org-risk")
    lines.append("auto-generated children: " + (
        ", ".join(c["child"] for c in ac) if ac else "none detected"))
    if fp.get("profiled"):
        lines.append(f"field population: profiled ({fp.get('total_rows')} rows, "
                     f"{len(fp['fields'])} field(s))")
    else:
        lines.append("field population: NOT profiled -- run profile-salesforce")
    return lines
