"""Structured, machine-readable data-shape profile per object (ROADMAP #83).

`describe()` tells you an object's *structure* (fields, types, relationships,
required flags). It can't tell you its *behavior* -- what the platform
auto-creates, what's really populated, what automation fires. This module
aggregates the behavioral signals the framework already produces into one
per-object JSON profile a tool can reason over:

- **structure** -- from live `describe()` (key/required fields, parent lookups).
- **automation** -- from `analyze-org-risk`'s `ObjectAutomationRisk` (active
  validation rules / triggers / flows / workflow rules / approval processes).
- **auto_generated_children** -- from `child_record_risk.py`'s empirical
  detection (rows in `ObjectAutomationRisk` with `CheckType =
  AutoGeneratedChildRecord`) -- the Tooling-API-invisible platform automation
  that a plain metadata read misses entirely.
- **field_population** -- from `profile-salesforce`'s `FieldProfile` (real
  populated %, distinct counts) -- how the data actually lives, not just what
  the schema allows.

Read-only. `build_profile()` returns a dict; the CLI writes it to JSON and
prints a summary. Missing upstream signals are reported as `scanned: false` /
`profiled: false`, never as a silently-clean zero -- a not-yet-run
`analyze-org-risk` is different from "no automation".
"""
import datetime
import json
import os
from decimal import Decimal

from sqlalchemy import text

import sql_dialect


def _describe_structure(sf, object_name):
    d = getattr(sf, object_name).describe()
    key_fields = []
    parent_lookups = []
    for f in d["fields"]:
        if f.get("type") == "reference" and f.get("referenceTo") and f.get("createable"):
            parent_lookups.append({
                "field": f["name"],
                "references": list(f["referenceTo"]),
                "relationshipName": f.get("relationshipName"),
            })
        # "required in practice" = not nillable AND not platform-defaulted
        required = (not f.get("nillable", True)) and (not f.get("defaultedOnCreate", False))
        if required or f.get("externalId") or f["name"] == "Name":
            key_fields.append({
                "name": f["name"],
                "type": f.get("type"),
                "required": bool(required),
                "createable": bool(f.get("createable")),
                "updateable": bool(f.get("updateable")),
                "defaultedOnCreate": bool(f.get("defaultedOnCreate")),
                "externalId": bool(f.get("externalId")),
            })
    # Surface same-object start/end date pairs (ROADMAP #88) so the ordering
    # risk is visible per object -- reuses snowfakery_data's own heuristic so
    # the profile and the mock generator agree on what a "date range" is.
    # Lazy import: keep this module light unless a profile is actually built.
    import snowfakery_data as _sfd
    date_names = [f["name"] for f in d["fields"]
                  if f.get("type") in ("date", "datetime")]
    date_range_pairs = [{"start": s, "end": e}
                        for s, e in _sfd.date_range_pairs(date_names)]

    return {
        "custom": bool(d.get("custom")),
        "key_fields": key_fields,
        "parent_lookups": parent_lookups,
        "date_range_pairs": date_range_pairs,
    }


def _automation_and_children(engine, object_name, schema):
    """Returns (automation_dict, auto_generated_children_list) from
    ObjectAutomationRisk. automation['scanned'] is False (not an empty
    count) when analyze-org-risk hasn't populated the table for this org."""
    d = sql_dialect.for_engine(engine)
    if not d.table_exists(engine, schema, "ObjectAutomationRisk"):
        return {"scanned": False}, []
    with engine.begin() as cx:
        rows = cx.execute(
            text(
                f"SELECT CheckType, ItemName, IsActive, DirectHit, Detail "
                f"FROM {d.qualify(schema, 'ObjectAutomationRisk')} "
                f"WHERE ObjectName = :obj"
            ),
            {"obj": object_name},
        ).mappings().all()
    rows = [sql_dialect.lower_keys(r) for r in rows]
    if not rows:
        # table exists but this object was never scanned
        return {"scanned": False}, []
    active_counts = {}
    auto_children = []
    for r in rows:
        ct = r.get("checktype")
        if ct == "AutoGeneratedChildRecord":
            auto_children.append({"child": r.get("itemname"), "detail": r.get("detail")})
        elif r.get("isactive"):
            active_counts[ct] = active_counts.get(ct, 0) + 1
    return {"scanned": True, "active_counts": active_counts}, auto_children


def _as_float(v):
    """Coerce a SQL numeric to a JSON-serializable float; None stays None.
    SQL Server returns NUMERIC/DECIMAL columns (e.g. FieldProfile.PopulatedPct)
    as Python Decimal, which json.dump can't serialize."""
    return None if v is None else float(v)


def _as_int(v):
    """Coerce a SQL count (Decimal/float on some backends) to a plain int;
    None stays None."""
    return None if v is None else int(v)


def _jsonable(o):
    """json.dump default hook: coerce any stray SQL numeric (Decimal) to a
    float so profile serialization never dies on a backend-specific type,
    even for a value a future field forgets to coerce at the source."""
    if isinstance(o, Decimal):
        return float(o)
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")


def _field_population(engine, object_name, schema):
    d = sql_dialect.for_engine(engine)
    if not d.table_exists(engine, schema, "FieldProfile"):
        return {"profiled": False}
    with engine.begin() as cx:
        rows = cx.execute(
            text(
                f"SELECT FieldName, PopulatedPct, DistinctCount, TotalRows "
                f"FROM {d.qualify(schema, 'FieldProfile')} "
                f"WHERE ObjectOrTable = :obj"
            ),
            {"obj": object_name},
        ).mappings().all()
    rows = [sql_dialect.lower_keys(r) for r in rows]
    if not rows:
        return {"profiled": False}
    fields = [{
        "name": r.get("fieldname"),
        "populated_pct": _as_float(r.get("populatedpct")),
        "distinct": _as_int(r.get("distinctcount")),
    } for r in rows]
    return {"profiled": True, "total_rows": _as_int(rows[0].get("totalrows")), "fields": fields}


def build_profile(sf, engine, object_name, schema="dbo", org_alias=None):
    """Assemble the full data-shape profile dict for one object."""
    automation, auto_children = _automation_and_children(engine, object_name, schema)
    return {
        "object": object_name,
        "org_alias": org_alias,
        "generated": datetime.date.today().isoformat(),
        "structure": _describe_structure(sf, object_name),
        "automation": automation,
        "auto_generated_children": auto_children,
        "field_population": _field_population(engine, object_name, schema),
    }


def profile_path(object_name, output_dir="data_shapes"):
    return os.path.join(output_dir, f"{object_name}.json")


def write_profile(profile, output_dir="data_shapes"):
    os.makedirs(output_dir, exist_ok=True)
    path = profile_path(profile["object"], output_dir)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(profile, fh, indent=2, default=_jsonable)
    return path


def load_profile(object_name, output_dir="data_shapes"):
    """Read a previously-built profile, or None if it doesn't exist -- the
    read-only surfacing side (show-data-shape), analogous to okf_lookup."""
    path = profile_path(object_name, output_dir)
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def _api_name_kind(name):
    """Classify a field/relationship API name for cloud-level portability:

    - ``standard`` -- no custom suffix (``DonorId``, ``Name``, ``RecordTypeId``):
      cloud-true, present in every org of the cloud.
    - ``packaged`` -- namespaced custom (``ns__Foo__c``): delivered by a
      managed package, so cloud-true for any org licensed for that package.
    - ``org_custom`` -- un-namespaced custom (``Foo__c``, including migration
      helpers like ``MigrationID__c``): added per-org, NOT portable.

    Recognizes the person-account custom suffixes ``__pc`` (field) and ``__pr``
    (relationship) too, not just ``__c``/``__r``/``__x`` -- a person-account
    org-custom field like ``SDO_Foo__pc`` is every bit as org-specific as a
    plain ``Foo__c`` and must be stripped the same way (found live: SDO
    person-account custom fields leaking into generalized Sales Cloud IP).

    Only ``standard`` and ``packaged`` survive generalization -- an org's own
    custom fields and this framework's own migration-key fields don't describe
    the *cloud*, so they'd be noise (or misleading) in shared IP.
    """
    n = name or ""
    if not (n.endswith("__c") or n.endswith("__r") or n.endswith("__x")
            or n.endswith("__pc") or n.endswith("__pr")):
        return "standard"
    base = n.rsplit("__", 1)[0]  # 'ns__Foo' (packaged) or 'Foo' (org custom)
    return "packaged" if "__" in base else "org_custom"


def generalize_profile(profile, cloud):
    """Promote an org-derived profile (:func:`build_profile`'s output) to
    cloud-level, reusable knowledge (ROADMAP #83).

    Strips everything org-specific -- the org alias, org/admin custom fields,
    *this* org's active-automation counts, *this* org's field population, and
    the numeric auto-generation rates -- and keeps only what's true of the
    **cloud itself** for any org on it: the standard/packaged structure, the
    auto-generated-child *relationships* (which children, not the rate), and
    the same-object date-range pairs. The result is committed, shareable IP a
    NEW project on the same cloud can consult before it has ever touched its
    own org. No org connection needed -- this reads an already-built profile.
    """
    st = profile.get("structure", {})
    key_fields = [f for f in st.get("key_fields", [])
                  if _api_name_kind(f.get("name")) != "org_custom"]
    parent_lookups = [p for p in st.get("parent_lookups", [])
                      if _api_name_kind(p.get("field")) != "org_custom"]
    # A date-range pair is cloud-portable only if BOTH endpoints are -- an
    # org-custom field on either end (e.g. Product2's Start_Date_Time__c)
    # makes the whole pair org-specific, so drop it (found live: SDO Product2
    # custom date pairs leaking into generalized Sales Cloud IP).
    date_range_pairs = [
        pair for pair in st.get("date_range_pairs", [])
        if _api_name_kind(pair.get("start")) != "org_custom"
        and _api_name_kind(pair.get("end")) != "org_custom"
    ]
    children = [c.get("child") for c in profile.get("auto_generated_children", [])
                if c.get("child")]
    return {
        "object": profile["object"],
        "cloud": cloud,
        "kind": "cloud-data-shape",
        "generalized": datetime.date.today().isoformat(),
        "note": (
            "Cloud-level data shape, generalized from a live org profile with "
            "org-specific detail removed (org custom fields, this org's active "
            "automation counts, field population, and numeric auto-generation "
            "rates). Structure, auto-generated-child relationships, and "
            "date-range pairs are platform-standard and portable; automation "
            "and population are org config/data -- run analyze-org-risk and "
            "profile-salesforce against your own org."
        ),
        "structure": {
            "custom_object": st.get("custom", False),
            "key_fields": key_fields,
            "parent_lookups": parent_lookups,
            "date_range_pairs": date_range_pairs,
        },
        "auto_generated_children": children,
    }


def cloud_profile_path(object_name, cloud, okf_dir="okf"):
    return os.path.join(okf_dir, cloud, "data-shapes", f"{object_name}.json")


def write_cloud_profile(cloud_profile, okf_dir="okf"):
    path = cloud_profile_path(cloud_profile["object"], cloud_profile["cloud"], okf_dir)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(cloud_profile, fh, indent=2, default=_jsonable)
    return path


def load_cloud_profile(object_name, cloud, okf_dir="okf"):
    path = cloud_profile_path(object_name, cloud, okf_dir)
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def find_cloud_profiles(objects=None, okf_dir="okf"):
    """Committed cloud-level profiles (``okf/<cloud>/data-shapes/<Object>.json``)
    matching any of ``objects`` (exact object-name match, case-insensitive),
    or all of them when ``objects`` is falsy. Lets ``gather-okf`` surface the
    machine-readable cloud shape alongside the prose OKF docs -- knowledge a
    fresh clone HAS (these are committed) even before it profiles its own org.
    Returns dicts: ``{path, object, cloud, profile}``.
    """
    if not os.path.isdir(okf_dir):
        return []
    wanted = {str(o).lower() for o in (objects or []) if o and str(o).strip()}
    found = []
    for cloud in sorted(os.listdir(okf_dir)):
        ds_dir = os.path.join(okf_dir, cloud, "data-shapes")
        if not os.path.isdir(ds_dir):
            continue
        for fname in sorted(os.listdir(ds_dir)):
            if not fname.lower().endswith(".json"):
                continue
            obj = fname[:-5]
            if wanted and obj.lower() not in wanted:
                continue
            path = os.path.join(ds_dir, fname)
            try:
                with open(path, encoding="utf-8") as fh:
                    profile = json.load(fh)
            except (OSError, ValueError):
                continue
            found.append({
                "path": path.replace(os.sep, "/"),
                "object": obj,
                "cloud": cloud,
                "profile": profile,
            })
    return found


def cloud_summary_lines(cp):
    """Compact, human-readable lines for a cloud-level profile -- the
    generalize/show/gather commands' shared renderer, mirroring
    :func:`summary_lines` for org profiles."""
    st = cp.get("structure", {})
    lines = [
        f"structure: {len(st.get('key_fields', []))} standard/packaged key "
        f"field(s), {len(st.get('parent_lookups', []))} standard/packaged "
        f"parent lookup(s), custom_object={st.get('custom_object')}",
    ]
    drp = st.get("date_range_pairs") or []
    if drp:
        lines.append("date-range pairs (end must be >= start): "
                     + ", ".join(f"{p['start']}->{p['end']}" for p in drp))
    ch = cp.get("auto_generated_children") or []
    lines.append("auto-created child relationships (verify against your own "
                 "org before inserting -- see note): " + (", ".join(ch) if ch else "none"))
    return lines


def summary_lines(profile):
    """Compact, human-readable lines describing a profile -- shared by the
    build and show CLI commands."""
    st = profile["structure"]
    au = profile["automation"]
    ac = profile["auto_generated_children"]
    fp = profile["field_population"]
    lines = [
        f"structure: {len(st['key_fields'])} key/required field(s), "
        f"{len(st['parent_lookups'])} parent lookup(s), custom={st['custom']}",
    ]
    drp = st.get("date_range_pairs") or []
    if drp:
        lines.append("date-range pairs (end must be >= start): "
                     + ", ".join(f"{p['start']}->{p['end']}" for p in drp))
    if au.get("scanned"):
        counts = au.get("active_counts") or {}
        lines.append("automation: " + (
            ", ".join(f"{k}={v}" for k, v in sorted(counts.items())) if counts
            else "no active automation found"))
    else:
        lines.append("automation: NOT scanned -- run analyze-org-risk")
    lines.append("auto-generated children: " + (
        ", ".join(c["child"] for c in ac) if ac else "none detected"))
    if fp.get("profiled"):
        lines.append(f"field population: profiled ({fp.get('total_rows')} rows, "
                     f"{len(fp['fields'])} field(s))")
    else:
        lines.append("field population: NOT profiled -- run profile-salesforce")
    return lines
