import pandas as pd
import pytest

import data_shape as ds
import sql_client
from config import Settings


@pytest.fixture
def sqlite_engine(tmp_path):
    s = Settings(sql_backend="sqlite", sql_sqlite_dir=str(tmp_path / "_sqlite"),
                 sql_sqlite_schemas="dbo")
    return sql_client.make_engine(s)


class _StubDescribe:
    def __init__(self, payload):
        self._payload = payload

    def describe(self):
        return self._payload


class _StubSF:
    """getattr(sf, 'GiftCommitment').describe() -> the canned payload."""
    def __init__(self, payload):
        self._payload = payload

    def __getattr__(self, name):
        return _StubDescribe(self._payload)


_DESCRIBE = {
    "custom": False,
    "fields": [
        {"name": "Id", "type": "id", "nillable": True, "createable": False},
        # required in practice: not nillable, not defaulted
        {"name": "Name", "type": "string", "nillable": False,
         "defaultedOnCreate": False, "createable": True, "updateable": True},
        # a real parent lookup (reference + createable)
        {"name": "DonorId", "type": "reference", "referenceTo": ["Account"],
         "relationshipName": "Donor", "nillable": False,
         "defaultedOnCreate": False, "createable": True, "updateable": True},
        # not required (nillable), not an external id, not Name -> excluded from key_fields
        {"name": "Description", "type": "textarea", "nillable": True,
         "defaultedOnCreate": False, "createable": True, "updateable": True},
        # external id -> included in key_fields even though nillable
        {"name": "MigrationID__c", "type": "string", "nillable": True,
         "defaultedOnCreate": False, "createable": True, "updateable": True,
         "externalId": True},
    ],
}


def _seed_automation(engine):
    pd.DataFrame({
        "ObjectName": ["GiftCommitment", "GiftCommitment", "GiftCommitment", "GiftCommitment"],
        "CheckType": ["ValidationRule", "ApexTrigger", "AutoGeneratedChildRecord", "ValidationRule"],
        "ItemName": ["VR_One", "Trig_One", "GiftCommitmentSchedule", "VR_Inactive"],
        "IsActive": [True, True, True, False],
        "DirectHit": [False, False, False, False],
        "Detail": ["", "", "6/10 have a schedule (60%)", ""],
        "AnalyzedDate": ["2026-07-26"] * 4,
    }).to_sql("ObjectAutomationRisk", engine, schema="dbo", if_exists="replace", index=False)


def _seed_fieldprofile(engine):
    pd.DataFrame({
        "ObjectOrTable": ["GiftCommitment", "GiftCommitment"],
        "SourceType": ["salesforce", "salesforce"],
        "FieldName": ["Name", "Description"],
        "DataType": ["string", "textarea"],
        "TotalRows": [15, 15],
        "PopulatedCount": [15, 3],
        "PopulatedPct": [1.0, 0.2],
        "NullCount": [0, 12], "BlankCount": [0, 0], "DistinctCount": [15, 3],
        "MinValue": [None, None], "MaxValue": [None, None],
        "MinLength": [None, None], "MaxLength": [None, None],
        "AnalyzedDate": ["2026-07-26", "2026-07-26"],
    }).to_sql("FieldProfile", engine, schema="dbo", if_exists="replace", index=False)


def test_structure_from_describe(sqlite_engine):
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment", org_alias="ORG")
    st = p["structure"]
    assert st["custom"] is False
    names = {f["name"] for f in st["key_fields"]}
    # Name (required), DonorId (required), MigrationID__c (external id) in; Description out
    assert names == {"Name", "DonorId", "MigrationID__c"}
    assert next(f for f in st["key_fields"] if f["name"] == "Name")["required"] is True
    assert next(f for f in st["key_fields"] if f["name"] == "MigrationID__c")["externalId"] is True
    assert st["parent_lookups"] == [
        {"field": "DonorId", "references": ["Account"], "relationshipName": "Donor"}]


def test_automation_and_auto_children_aggregated(sqlite_engine):
    _seed_automation(sqlite_engine)
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment")
    assert p["automation"]["scanned"] is True
    # only ACTIVE rows counted; inactive VR excluded
    assert p["automation"]["active_counts"] == {"ValidationRule": 1, "ApexTrigger": 1}
    assert p["auto_generated_children"] == [
        {"child": "GiftCommitmentSchedule", "detail": "6/10 have a schedule (60%)"}]


def test_field_population_aggregated(sqlite_engine):
    _seed_fieldprofile(sqlite_engine)
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment")
    fp = p["field_population"]
    assert fp["profiled"] is True and fp["total_rows"] == 15
    assert {f["name"] for f in fp["fields"]} == {"Name", "Description"}


def test_not_scanned_not_profiled_fallbacks(sqlite_engine):
    # neither table exists -> honest false, not a misleading clean zero
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment")
    assert p["automation"] == {"scanned": False}
    assert p["auto_generated_children"] == []
    assert p["field_population"] == {"profiled": False}


def test_table_exists_but_object_never_scanned(sqlite_engine):
    _seed_automation(sqlite_engine)
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "SomeOtherObject")
    assert p["automation"] == {"scanned": False}  # no rows for this object


def test_write_and_load_round_trip(sqlite_engine, tmp_path):
    _seed_automation(sqlite_engine)
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment", org_alias="ORG")
    out = str(tmp_path / "shapes")
    path = ds.write_profile(p, out)
    assert path.endswith("GiftCommitment.json")
    loaded = ds.load_profile("GiftCommitment", out)
    assert loaded == p
    assert ds.load_profile("Nope", out) is None


def test_jsonable_coerces_decimal_to_float():
    """SQL Server returns FieldProfile.PopulatedPct as Decimal, which
    json.dump can't serialize -- it crashed build-data-shape-profile the
    first time it ran on a SQL-Server-backed org (the SDO, 2026-07-31).
    SQLite (this file's other fixtures) never yields Decimal, so the bug
    hid until real SQL Server data hit it. The default hook coerces it."""
    from decimal import Decimal
    result = ds._jsonable(Decimal("99.71"))
    assert result == 99.71 and isinstance(result, float)
    with pytest.raises(TypeError):
        ds._jsonable(object())


def test_write_profile_serializes_decimal_field_population(tmp_path):
    """Regression for the SDO crash: a profile carrying Decimal values (as
    SQL Server produces for PopulatedPct) must write and round-trip to plain
    floats rather than raising 'Object of type Decimal is not JSON
    serializable'."""
    from decimal import Decimal
    profile = {
        "object": "Opportunity",
        "field_population": {
            "profiled": True,
            "total_rows": 685,
            "fields": [{"name": "Amount", "populated_pct": Decimal("99.71"), "distinct": 188}],
        },
    }
    out = str(tmp_path / "shapes")
    ds.write_profile(profile, out)
    loaded = ds.load_profile("Opportunity", out)
    pct = loaded["field_population"]["fields"][0]["populated_pct"]
    assert pct == 99.71 and isinstance(pct, float)


def test_summary_lines_report_missing_signals(sqlite_engine):
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment")
    text = "\n".join(ds.summary_lines(p))
    assert "NOT scanned" in text and "NOT profiled" in text


# --- cloud-level generalization (ROADMAP #83) -------------------------------

def test_api_name_kind_classifies_portability():
    assert ds._api_name_kind("DonorId") == "standard"
    assert ds._api_name_kind("RecordTypeId") == "standard"
    assert ds._api_name_kind("MigrationID__c") == "org_custom"
    assert ds._api_name_kind("Foo__c") == "org_custom"
    # namespaced managed-package field is cloud-true for any licensed org
    assert ds._api_name_kind("npsp__Amount__c") == "packaged"
    assert ds._api_name_kind("ns__Rel__r") == "packaged"


def test_generalize_strips_org_specifics(sqlite_engine):
    _seed_automation(sqlite_engine)
    _seed_fieldprofile(sqlite_engine)
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment",
                         org_alias="NPC_TARGET_v2")
    cp = ds.generalize_profile(p, "nonprofit-cloud")

    # provenance / no org identity
    assert cp["cloud"] == "nonprofit-cloud"
    assert cp["kind"] == "cloud-data-shape"
    assert "org_alias" not in cp
    # org-specific behavioral detail is gone entirely
    assert "automation" not in cp
    assert "field_population" not in cp

    # org custom field (MigrationID__c) dropped; standard fields kept
    key_names = {f["name"] for f in cp["structure"]["key_fields"]}
    assert key_names == {"Name", "DonorId"}
    assert cp["structure"]["parent_lookups"] == [
        {"field": "DonorId", "references": ["Account"], "relationshipName": "Donor"}]

    # auto-generated children reduced to the relationship (name), not the rate
    assert cp["auto_generated_children"] == ["GiftCommitmentSchedule"]
    # detail string carrying "6/10 ... (60%)" must not survive anywhere
    import json as _json
    assert "60%" not in _json.dumps(cp)


def test_generalize_keeps_packaged_field():
    profile = {
        "object": "npsp__Allocation__c",
        "org_alias": "SOME_ORG",
        "structure": {
            "custom": True,
            "key_fields": [
                {"name": "Name"},
                {"name": "npsp__Amount__c", "externalId": False},  # packaged -> kept
                {"name": "MigrationID__c", "externalId": True},     # org custom -> dropped
            ],
            "parent_lookups": [
                {"field": "npsp__Opportunity__c", "references": ["Opportunity"]},
                {"field": "Local_Lookup__c", "references": ["Account"]},
            ],
            "date_range_pairs": [],
        },
        "automation": {"scanned": True, "active_counts": {"ValidationRule": 3}},
        "auto_generated_children": [],
    }
    cp = ds.generalize_profile(profile, "npsp")
    assert {f["name"] for f in cp["structure"]["key_fields"]} == {"Name", "npsp__Amount__c"}
    assert [p["field"] for p in cp["structure"]["parent_lookups"]] == ["npsp__Opportunity__c"]
    assert cp["structure"]["custom_object"] is True


def test_cloud_profile_write_load_and_find(tmp_path):
    okf_dir = str(tmp_path / "okf")
    cp = {
        "object": "GiftCommitment", "cloud": "nonprofit-cloud",
        "structure": {"custom_object": False, "key_fields": [], "parent_lookups": [],
                      "date_range_pairs": [{"start": "EffectiveStartDate", "end": "ExpectedEndDate"}]},
        "auto_generated_children": ["GiftCommitmentSchedule"],
    }
    path = ds.write_cloud_profile(cp, okf_dir)
    assert path.endswith("nonprofit-cloud/data-shapes/GiftCommitment.json".replace("/", __import__("os").sep))
    assert ds.load_cloud_profile("GiftCommitment", "nonprofit-cloud", okf_dir) == cp
    assert ds.load_cloud_profile("Nope", "nonprofit-cloud", okf_dir) is None

    # find_cloud_profiles matches by object name across clouds
    ds.write_cloud_profile({"object": "Account", "cloud": "sales-cloud",
                            "structure": {}, "auto_generated_children": []}, okf_dir)
    hits = ds.find_cloud_profiles(objects=["GiftCommitment"], okf_dir=okf_dir)
    assert [h["object"] for h in hits] == ["GiftCommitment"]
    assert hits[0]["cloud"] == "nonprofit-cloud"
    # no filter -> every committed profile
    assert {h["object"] for h in ds.find_cloud_profiles(okf_dir=okf_dir)} == {"GiftCommitment", "Account"}
    # nonexistent okf dir -> [] not error
    assert ds.find_cloud_profiles(okf_dir=str(tmp_path / "missing")) == []


def test_cloud_summary_lines_flag_children_and_dates():
    cp = {
        "structure": {"custom_object": False, "key_fields": [{}, {}],
                      "parent_lookups": [{}],
                      "date_range_pairs": [{"start": "StartDate", "end": "EndDate"}]},
        "auto_generated_children": ["GiftTransaction"],
    }
    text = "\n".join(ds.cloud_summary_lines(cp))
    assert "StartDate->EndDate" in text
    assert "GiftTransaction" in text
    assert "auto-created child relationships" in text
