import pandas as pd
import pytest

import data_shape as ds
import sql_client
from config import Settings


@pytest.fixture
def sqlite_engine(tmp_path):
    s = Settings(sql_backend="sqlite", sql_sqlite_dir=str(tmp_path / "_sqlite"),
                 sql_sqlite_schemas="dbo")
    return sql_client.make_engine(s)


class _StubDescribe:
    def __init__(self, payload):
        self._payload = payload

    def describe(self):
        return self._payload


class _StubSF:
    """getattr(sf, 'GiftCommitment').describe() -> the canned payload."""
    def __init__(self, payload):
        self._payload = payload

    def __getattr__(self, name):
        return _StubDescribe(self._payload)


_DESCRIBE = {
    "custom": False,
    "fields": [
        {"name": "Id", "type": "id", "nillable": True, "createable": False},
        # required in practice: not nillable, not defaulted
        {"name": "Name", "type": "string", "nillable": False,
         "defaultedOnCreate": False, "createable": True, "updateable": True},
        # a real parent lookup (reference + createable)
        {"name": "DonorId", "type": "reference", "referenceTo": ["Account"],
         "relationshipName": "Donor", "nillable": False,
         "defaultedOnCreate": False, "createable": True, "updateable": True},
        # not required (nillable), not an external id, not Name -> excluded from key_fields
        {"name": "Description", "type": "textarea", "nillable": True,
         "defaultedOnCreate": False, "createable": True, "updateable": True},
        # external id -> included in key_fields even though nillable
        {"name": "MigrationID__c", "type": "string", "nillable": True,
         "defaultedOnCreate": False, "createable": True, "updateable": True,
         "externalId": True},
    ],
}


def _seed_automation(engine):
    pd.DataFrame({
        "ObjectName": ["GiftCommitment", "GiftCommitment", "GiftCommitment", "GiftCommitment"],
        "CheckType": ["ValidationRule", "ApexTrigger", "AutoGeneratedChildRecord", "ValidationRule"],
        "ItemName": ["VR_One", "Trig_One", "GiftCommitmentSchedule", "VR_Inactive"],
        "IsActive": [True, True, True, False],
        "DirectHit": [False, False, False, False],
        "Detail": ["", "", "6/10 have a schedule (60%)", ""],
        "AnalyzedDate": ["2026-07-26"] * 4,
    }).to_sql("ObjectAutomationRisk", engine, schema="dbo", if_exists="replace", index=False)


def _seed_fieldprofile(engine):
    pd.DataFrame({
        "ObjectOrTable": ["GiftCommitment", "GiftCommitment"],
        "SourceType": ["salesforce", "salesforce"],
        "FieldName": ["Name", "Description"],
        "DataType": ["string", "textarea"],
        "TotalRows": [15, 15],
        "PopulatedCount": [15, 3],
        "PopulatedPct": [1.0, 0.2],
        "NullCount": [0, 12], "BlankCount": [0, 0], "DistinctCount": [15, 3],
        "MinValue": [None, None], "MaxValue": [None, None],
        "MinLength": [None, None], "MaxLength": [None, None],
        "AnalyzedDate": ["2026-07-26", "2026-07-26"],
    }).to_sql("FieldProfile", engine, schema="dbo", if_exists="replace", index=False)


def test_structure_from_describe(sqlite_engine):
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment", org_alias="ORG")
    st = p["structure"]
    assert st["custom"] is False
    names = {f["name"] for f in st["key_fields"]}
    # Name (required), DonorId (required), MigrationID__c (external id) in; Description out
    assert names == {"Name", "DonorId", "MigrationID__c"}
    assert next(f for f in st["key_fields"] if f["name"] == "Name")["required"] is True
    assert next(f for f in st["key_fields"] if f["name"] == "MigrationID__c")["externalId"] is True
    assert st["parent_lookups"] == [
        {"field": "DonorId", "references": ["Account"], "relationshipName": "Donor"}]


def test_automation_and_auto_children_aggregated(sqlite_engine):
    _seed_automation(sqlite_engine)
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment")
    assert p["automation"]["scanned"] is True
    # only ACTIVE rows counted; inactive VR excluded
    assert p["automation"]["active_counts"] == {"ValidationRule": 1, "ApexTrigger": 1}
    assert p["auto_generated_children"] == [
        {"child": "GiftCommitmentSchedule", "detail": "6/10 have a schedule (60%)"}]


def test_field_population_aggregated(sqlite_engine):
    _seed_fieldprofile(sqlite_engine)
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment")
    fp = p["field_population"]
    assert fp["profiled"] is True and fp["total_rows"] == 15
    assert {f["name"] for f in fp["fields"]} == {"Name", "Description"}


def test_not_scanned_not_profiled_fallbacks(sqlite_engine):
    # neither table exists -> honest false, not a misleading clean zero
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment")
    assert p["automation"] == {"scanned": False}
    assert p["auto_generated_children"] == []
    assert p["field_population"] == {"profiled": False}


def test_table_exists_but_object_never_scanned(sqlite_engine):
    _seed_automation(sqlite_engine)
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "SomeOtherObject")
    assert p["automation"] == {"scanned": False}  # no rows for this object


def test_write_and_load_round_trip(sqlite_engine, tmp_path):
    _seed_automation(sqlite_engine)
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment", org_alias="ORG")
    out = str(tmp_path / "shapes")
    path = ds.write_profile(p, out)
    assert path.endswith("GiftCommitment.json")
    loaded = ds.load_profile("GiftCommitment", out)
    assert loaded == p
    assert ds.load_profile("Nope", out) is None


def test_summary_lines_report_missing_signals(sqlite_engine):
    p = ds.build_profile(_StubSF(_DESCRIBE), sqlite_engine, "GiftCommitment")
    text = "\n".join(ds.summary_lines(p))
    assert "NOT scanned" in text and "NOT profiled" in text
